# Generated by Django 3.0 on 2019-12-05 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.CharField(max_length=25)),
                ('manager', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigItemAttribute',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('valueType', models.CharField(blank=True, choices=[('', 'None'), ('AutoInt', 'Automaticly Assigned Integer'), ('AutoUUID', 'Automaticly Assigned UUID'), ('Boolean', 'Boolean'), ('Char', 'String'), ('Choice', 'List of Choices'), ('Credential', 'Credential'), ('Date', 'Date'), ('DateTime', 'Date and Time'), ('Email', 'Email'), ('File', 'File Upload Chooser'), ('Float', 'Float'), ('Image', 'Image Upload Chooser'), ('Integer', 'Integer'), ('GenericIPAddress', 'IP'), ('MultipleChoice', 'List of Choices with the ability to choose more than one'), ('MultipleInstance', 'List of Choices that you can have more than one of the same'), ('NullBoolean', 'True/False/None'), ('Regex', 'Regex'), ('Slug', 'Slug'), ('Time', 'Time'), ('URL', 'URL'), ('UserList', 'User List'), ('Password', 'Password'), ('YesNo', 'Yes/No')], default='', max_length=25)),
                ('valuePrompt', models.CharField(blank=True, default='', max_length=254)),
                ('valueDefault', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigItemTree',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('leafType', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=25)),
                ('configItems', models.ManyToManyField(blank=True, to='depo.ConfigItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigItemAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(default='')),
                ('configItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.ConfigItem')),
                ('configItemAttributeType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depo.ConfigItemAttribute')),
            ],
        ),
    ]
