# Generated by Django 3.0.8 on 2020-07-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.CharField(max_length=25)),
                ('manager', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigItemAttribute',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('valueType', models.CharField(blank=True, choices=[('', 'None'), ('AutoInt', 'Automaticly Assigned Integer'), ('AutoUUID', 'Automaticly Assigned UUID'), ('Boolean', 'Boolean'), ('Char', 'String'), ('Choice', 'List of Choices'), ('Credential', 'Credential'), ('Date', 'Date'), ('DateTime', 'Date and Time'), ('Email', 'Email'), ('File', 'File Upload Chooser'), ('Float', 'Float'), ('Image', 'Image Upload Chooser'), ('Integer', 'Integer'), ('GenericIPAddress', 'IP'), ('MultipleChoice', 'List of Choices with the ability to choose more than one'), ('MultipleInstance', 'List of Choices that you can have more than one of the same'), ('NullBoolean', 'True/False/None'), ('Regex', 'Regex'), ('Slug', 'Slug'), ('Time', 'Time'), ('URL', 'URL'), ('UserList', 'User List'), ('Password', 'Password'), ('YesNo', 'Yes/No')], default='', max_length=25)),
                ('valuePrompt', models.CharField(blank=True, default='', max_length=254)),
                ('valueDefault', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigItemRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigItemTree',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('leafType', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=25)),
                ('configItems', models.ManyToManyField(blank=True, to='depo.ConfigItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigItemConfigItemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolePriority', models.IntegerField(default=0, help_text="Importance of roll with this config item.  The first, highest priority roll is considered the 'primary' roll.", verbose_name='Role Priority')),
                ('ConfigItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.ConfigItem')),
                ('ConfigItemRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.ConfigItemRole')),
            ],
            options={
                'ordering': ['-rolePriority'],
            },
        ),
        migrations.CreateModel(
            name='ConfigItemAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(default='')),
                ('configItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.ConfigItem')),
                ('configItemAttributeType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depo.ConfigItemAttribute')),
            ],
        ),
        migrations.AddField(
            model_name='configitem',
            name='roles',
            field=models.ManyToManyField(through='depo.ConfigItemConfigItemRole', to='depo.ConfigItemRole'),
        ),
    ]
