# Generated by Django 3.0 on 2019-12-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItemRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
            ],
        )
    ]
