# Generated by Django 3.0 on 2019-12-31 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0002_auto_20191231_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='configitem',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='depo.ConfigItemRole'),
            preserve_default=False,
        ),
    ]
