# Generated by Django 3.0 on 2019-12-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0003_configitem_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configitem',
            name='role',
        ),
        migrations.AddField(
            model_name='configitem',
            name='roles',
            field=models.ManyToManyField(to='depo.ConfigItemRole'),
        ),
    ]
