# Generated by Django 3.0 on 2019-12-31 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0004_auto_20191231_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItemConfigItemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolePriority', models.IntegerField(default=0, help_text="Importance of roll with this config item.  The first, highest priority roll is considered the 'primary' roll.", verbose_name='Role Priority')),
                ('ConfigItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.ConfigItem')),
                ('ConfigItemRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.ConfigItemRole')),
            ],
            options={
                'ordering': ['rolePriority'],
            },
        ),
    ]
