# Generated by Django 3.0 on 2019-12-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('depo', '0004_auto_20191231_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='configitem',
            name='roles',
            field=models.ManyToManyField(through='depo.ConfigItemConfigItemRole', to='depo.ConfigItemRole'),
        ),
    ]
