# Generated by Django 3.0 on 2019-12-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0007_configitem_roles'),
        ('depo', '0006_remove_configitem_roles'),
        ('depo', '0005_auto_20191231_1116'),
    ]

    operations = [
    ]
