# Generated by Django 3.0.1 on 2020-01-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0008_merge_20191231_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configitemconfigitemrole',
            options={'ordering': ['-rolePriority']},
        ),
        migrations.AddField(
            model_name='configitem',
            name='roles',
            field=models.ManyToManyField(through='depo.ConfigItemConfigItemRole', to='depo.ConfigItemRole'),
        ),
    ]
